# Generated by Django 4.2.1 on 2023-05-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_remember_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remember',
            old_name='user',
            new_name='user_id',
        ),
    ]
