# Generated by Django 4.2.1 on 2023-05-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remember',
        ),
    ]
